# .github/workflows/ci.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'

      # Execute Gradle commands in GitHub Actions workflows
      # => https://github.com/marketplace/actions/gradle-build-action
      - name: Deletes the build directory
        uses: gradle/gradle-build-action@v3.1.0
        with:
            arguments: clean

      - name: Run the test suits
        uses: gradle/gradle-build-action@v3.1.0
        with:
          arguments: test
