name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * SUN"

jobs:
  update-gradle-wrapper:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
